graph TD
    N0[&quot;mama:Person<br>https://www.commoncoreontologies.org/ont00001262&quot;]
    N1[&quot;baby:Person<br>https://www.commoncoreontologies.org/ont00001262&quot;]

    N0 -- &quot;has interest in<br>https://www.commoncoreontologies.org/ont00001984&quot; --> N1
